import React,{useEffect,useMemo,useState} from "react";
import {UsersRound,Database,ShieldCheck,Trash2,UserCheck,UserX} from "lucide-react";
import {useAuth} from "../context/AuthContext";
import {api} from "../api";
export default function AdminDashboard(){const {users}=useAuth();const [cases,setCases]=useState([]);useEffect(()=>{api.getCases().then(setCases)},[]);
const counts=useMemo(()=>({users:users.length,authorities:users.filter(u=>u.role==="authority").length,admins:users.filter(u=>u.role==="admin").length,cases:cases.length}),[users,cases]);
return <div className="page-stack"><section className="section-heading"><div><span className="eyebrow">SYSTEM ADMINISTRATION</span><h2>Platform overview</h2><p>Manage registered accounts and monitor stored assessment records.</p></div></section>
<div className="grid gap-4 md:grid-cols-4"><div className="metric-card"><UsersRound/><span>Users</span><strong>{counts.users}</strong></div><div className="metric-card"><UserCheck/><span>Authorities</span><strong>{counts.authorities}</strong></div><div className="metric-card"><ShieldCheck/><span>Admins</span><strong>{counts.admins}</strong></div><div className="metric-card"><Database/><span>Cases</span><strong>{counts.cases}</strong></div></div>
<div className="panel table-panel"><div className="panel-header"><div><span className="eyebrow">ACCESS CONTROL</span><h3>Registered accounts</h3></div></div><div className="table-shell"><table className="modern-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><span className="status-text"><span className="status-dot"/>{u.role}</span></td><td>{u.status}</td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></div>
<div className="info-strip"><UserX size={17}/><span>For production, account creation and privileged role assignment should be enforced by your backend. This frontend stores accounts locally for development.</span></div></div>}
