import React,{useEffect,useState} from "react";
import {Activity,BarChart3,Database,TrendingUp} from "lucide-react";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip} from "recharts";
import {api} from "../api";
export default function Analytics(){const [overview,setOverview]=useState(null);const [risk,setRisk]=useState(null);const [svi,setSvi]=useState(null);const [signal,setSignal]=useState(null);const [error,setError]=useState("");
useEffect(()=>{Promise.all([api.getAnalyticsOverview(),api.getRiskDistribution(),api.getSVIStatistics(),api.getSignalFrequency()]).then(([o,r,s,f])=>{setOverview(o);setRisk(r);setSvi(s);setSignal(f)}).catch(e=>setError(e.message||"Unable to load analytics."))},[]);
if(error)return <div className="state-card error-state">{error}</div>;
if(!overview||!risk||!svi||!signal)return <div className="state-card"><div className="spinner"/><strong>Loading analytics…</strong></div>;
const riskData=["CRITICAL","HIGH","MODERATE","LOW"].map(x=>({name:x,value:Number(risk[x]||0)}));
const signals=["fear","immediate_threat","distress","isolation","intimidation","self_harm"].map(k=>({name:k.replaceAll("_"," "),value:Number(signal[k]||0)}));
const hasCases=overview.total_cases>0;
return <div className="page-stack"><section className="section-heading"><div><span className="eyebrow">OPERATIONS INTELLIGENCE</span><h2>Analytics</h2><p>Live analytics calculated by the assessment service.</p></div><div className="data-chip"><Database size={15}/>{overview.total_cases} total cases</div></section>
<div className="analytics-summary"><div><TrendingUp size={19}/><div><strong>{hasCases?Math.round(((risk.CRITICAL+risk.HIGH)/overview.total_cases)*100):0}%</strong><span>high or critical</span></div></div><div><Activity size={19}/><div><strong>6</strong><span>tracked signals</span></div></div><div><BarChart3 size={19}/><div><strong>{Math.round(svi.average)}</strong><span>average SVI</span></div></div></div>
{!hasCases?<div className="state-card"><BarChart3 size={28}/><strong>No analytics yet</strong><span>Complete an assessment to populate the charts.</span></div>:<><div className="analytics-grid"><div className="panel" style={{height:340}}><div className="panel-header"><div><span className="eyebrow">CASE MIX</span><h3>Risk distribution</h3></div></div><ResponsiveContainer width="100%" height="85%"><BarChart data={riskData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="Cases" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div>
<div className="panel" style={{height:340}}><div className="panel-header"><div><span className="eyebrow">SIGNAL PROFILE</span><h3>Detected signals</h3></div></div><ResponsiveContainer width="100%" height="85%"><BarChart data={signals} layout="vertical" margin={{left:25,right:15}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={85}/><Tooltip/><Bar dataKey="value" name="Cases" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></div>
<div className="panel" style={{height:340}}><div className="panel-header"><div><span className="eyebrow">SVI STATISTICS</span><h3>Score range</h3></div></div><div className="analytics-summary" style={{margin:20}}><div><TrendingUp size={19}/><div><strong>{Math.round(svi.minimum)}</strong><span>minimum SVI</span></div></div><div><Activity size={19}/><div><strong>{Math.round(svi.average)}</strong><span>average SVI</span></div></div><div><BarChart3 size={19}/><div><strong>{Math.round(svi.maximum)}</strong><span>maximum SVI</span></div></div></div></div></>}</div>}
