import React,{useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {ShieldCheck,UserRound,Building2,Settings,ArrowRight,Check} from "lucide-react";
import {useAuth} from "../context/AuthContext";
const roles=[{id:"user",title:"User",sub:"Submit assessments",icon:UserRound},{id:"authority",title:"Authority",sub:"Review & respond",icon:Building2},{id:"admin",title:"Admin",sub:"Manage platform",icon:Settings}];
export default function Signup(){const {register}=useAuth();const nav=useNavigate();const [role,setRole]=useState("user");const [form,setForm]=useState({name:"",email:"",phone:"",password:"",confirm:"",consent:false});const [error,setError]=useState("");
const submit=e=>{e.preventDefault();setError("");if(form.password.length<8)return setError("Password must be at least 8 characters.");if(form.password!==form.confirm)return setError("Passwords do not match.");if(!form.consent)return setError("Please accept the privacy and responsible-use terms.");try{const u=register({...form,role});nav(u.role==="admin"?"/admin/dashboard":u.role==="user"?"/user/dashboard":"/dashboard")}catch(err){setError(err.message)}};
return <div className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-5xl"><div className="flex justify-between"><Link to="/login" className="text-sm font-semibold text-slate-500">← Back to login</Link><div className="flex items-center gap-2 font-extrabold text-[#102f49]"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#102f49] text-white"><ShieldCheck size={18}/></span>SAHAYAK</div></div><div className="py-8 text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-600">Secure registration</p><h1 className="mt-2 text-3xl font-bold">Create your account</h1><p className="mt-2 text-sm text-slate-500">Select the workspace that matches your role.</p></div>
<div className="grid gap-4 md:grid-cols-3">{roles.map(r=>{const I=r.icon;return <button type="button" key={r.id} onClick={()=>setRole(r.id)} className={`rounded-2xl border p-5 text-left ${role===r.id?"border-teal-500 bg-teal-50 ring-2 ring-teal-500/10":"border-slate-200 bg-white"}`}><div className={`grid h-11 w-11 place-items-center rounded-xl ${role===r.id?"bg-teal-600 text-white":"bg-slate-100"}`}><I/></div><h3 className="mt-4 font-bold">{r.title}</h3><p className="mt-1 text-xs text-teal-700">{r.sub}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold">{role===r.id?<><Check size={14}/> Selected</>:"Select"}</span></button>})}</div>
<div className="mx-auto mt-6 max-w-3xl rounded-2xl border bg-white p-6 shadow-xl sm:p-8"><h2 className="font-bold">Account information</h2>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2">{[["name","Full name","text"],["email","Email address","email"],["phone","Phone number","tel"],["password","Password","password"],["confirm","Confirm password","password"]].map(([k,l,t])=><label key={k} className="text-sm font-semibold">{l}<input required className="mt-2 w-full rounded-xl border bg-slate-50 p-3 outline-none focus:border-teal-500" type={t} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label className="flex gap-3 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500"><input required type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>I agree to the privacy, consent and responsible-use policies.</span></label><button className="flex w-full justify-center gap-2 rounded-xl bg-[#102f49] py-3.5 font-bold text-white">Create account <ArrowRight size={17}/></button></form></div></div></div>}
